# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c505036b5578f373c50b455de1bf18bfcaf982fe2efd9db6ed595adcc114f5609aa481dfae1e100d767799d79c9d0ae321947b04893312c17c68800c5d2006bf

test:
  secret_key_base: 612f1295d40ff2bd4c3ae2fdbb4e4c33c54f729f3a305d649ea3da1d04f8d9b7e5388b1f30451c391f6c00a57395dc56b5a3181556b202ff6879eec59bad5d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
